export enum LanguageLabel {
    en = 'Print / Save PDF',
    es = 'Imprimir / Guardar PDF',
    fr = 'Imprimer / Enregistrer le PDF',
    de = 'Drucken / PDF speichern',
    it = 'Stampa / Salva PDF',
    pt = 'Imprimir / Salvar PDF',
    ru = 'Печать / Сохранить PDF',
    zh = '打印 / 保存 PDF',
    ja = '印刷 / PDF を保存',
    ko = '인쇄 / PDF 저장',
    ar = 'طباعة / حفظ PDF',
    hi = 'प्रिंट करें / PDF सहेजें',
    bn = 'প্রিন্ট / পিডিএফ সংরক্ষণ করুন',
    ur = 'پرنٹ کریں / PDF محفوظ کریں',
    tr = 'Yazdır / PDF Kaydet',
    nl = 'Afdrukken / PDF opslaan',
    pl = 'Drukuj / Zapisz PDF',
    sv = 'Skriv ut / Spara PDF',
    ro = 'Printează / Salvează PDF',
    fa = 'چاپ / ذخیره PDF',
  }