name: Deploy on commit to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Get theme from .env
        id: get-theme
        run: |
          DEFAULT_THEME="github"
          if [ -f .env ]; then
            # Read the entire file into a variable
            ENV_CONTENT=$(cat .env)
            # Use grep with word boundaries and capture the value
            if THEME_LINE=$(echo "$ENV_CONTENT" | grep -E "^VITE_CV_THEME="); then
              # Extract everything after the = sign and remove quotes
              THEME=$(echo "$THEME_LINE" | sed 's/^VITE_CV_THEME=//' | sed 's/^["'"'"']//;s/["'"'"']$//')
              if [ -n "$THEME" ]; then
                echo "Found theme in .env: ${THEME}"
                echo "theme=${THEME}" >> $GITHUB_OUTPUT
                exit 0
              fi
            fi
          fi
          echo "Using default theme: ${DEFAULT_THEME}"
          echo "theme=${DEFAULT_THEME}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          VITE_CV_THEME: ${{ steps.get-theme.outputs.theme }}
        run: |
          echo "Building with theme: $VITE_CV_THEME"
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: PrBart/PrBart.github.io
          publish_branch: gh-pages
          publish_dir: ./dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com 