name: Deploy on commit to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Load environment variables from .env
        run: |
          echo "Loading .env"
          set -a
          source .env
          set +a
          echo "Environment variables loaded:"
          echo "VITE_CV_THEME=$VITE_CV_THEME"
        shell: bash

      - name: Install dependencies
        run: npm ci

      - name: Build with selected theme
        run: |
          echo "Building with theme: $VITE_CV_THEME"
          npm run build
        env:
          VITE_CV_THEME: ${{ env.VITE_CV_THEME }}

      - name: Copy 404 fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: PrBart/PrBart.github.io
          publish_branch: gh-pages
          publish_dir: ./dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
