name: Deploy with the github theme

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build:github
          cp dist/index.html dist/404.html
        env:
          VITE_CV_THEME: github

      - name: Deploy to GitHub Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          external_repository: PrBart/PrBart.github.io
          publish_branch: gh-pages
          publish_dir: ./dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
